In [4]:
#1. First things first, here is an example of NumPy
import numpy as np
x=np.array([[1,2,3],[5,6,7]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [5 6 7]]


In [5]:
#2. SciPy is a library for scientific computing.
from scipy import sparse
#create a 2D NumPy array with zeros everywhere else
eye=np.eye(4)

print("NumPy array:\n{}".format(eye))

NumPy array:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [6]:
#3. Convert the NumPy array to a SciPy sparse array in CSR format
# 1s along the diagonal, 0s everywhere else
sparse_matrix=sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [18]:
from IPython.display import Latex
Latex(r"""\begin{eqnarray}
\mathop{\int}\limits_{0}\limits^{\mathit{\pi}}{\cos{\mathrm{(}}{x}{\mathrm{)}}\hspace{0.33em}{dx}}\hspace{0.33em}\mathrm{{=}}\hspace{0.33em}{1}
\end{eqnarray}""")

<IPython.core.display.Latex object>